# Generated by Django 4.0 on 2024-07-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_appointment_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('specialty', models.CharField(blank=True, default='', max_length=100)),
                ('capacity', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
