# Generated by Django 4.0 on 2024-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
